class Solution:
    def reorderLogFiles(self, logs: List[str]) -> List[str]:
        def get_key(log: str):
            identifier, rest = log.split(" ", 1)
        # We return a tuple that contains a flag indicating whether it's a digit log,
        # the log content (for letter logs) or a tuple of 0s for number logs (to ensure they're ordered as they appear),
        # and the identifier (which serves as a tie-breaker if the log content is the same).
            return (0, rest, identifier) if rest[0].isalpha() else (1,)

        # The sorted function uses the key generated by the get_key function to sort the logs.
        return sorted(logs, key=get_key)